application: diddit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
- url: /api/.*
  script: api.app
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /img
  static_dir: img
  

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
